basePath: /
definitions:
  context-awareness-manager_internal_models.DockerContextDefinition:
    properties:
      id:
        type: string
      imageId:
        type: string
    type: object
  context-awareness-manager_internal_models.Result:
    properties:
      classification:
        type: string
      id:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API API for managing Docker context and roles in the COLMENA project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Context Awareness Manager API
  version: "1.0"
paths:
  /context:
    post:
      consumes:
      - application/json
      description: Endpoint to receive and process Docker context
      parameters:
      - description: Context to process
        in: body
        name: context
        required: true
        schema:
          $ref: '#/definitions/context-awareness-manager_internal_models.DockerContextDefinition'
      produces:
      - application/json
      responses:
        "200":
          description: Context processed successfully
          schema:
            $ref: '#/definitions/context-awareness-manager_internal_models.Result'
        "400":
          description: Invalid context
          schema:
            type: string
      summary: Receive context
      tags:
      - Context
  /health:
    get:
      description: Checks if the service is up and responding.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check API health
      tags:
      - Health
securityDefinitions:
  Bearer:
    description: '"Type ''Bearer TOKEN'' to correctly set the API Key"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
