# Prometheus configuration
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus-colmena-1"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-exporter-colmena-1"
    scrape_timeout: 25s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["node-exporter:9100"]

remote_write:
  - url: "http://thanos-receive.192.168.137.25.nip.io/api/v1/receive"
