services:
  context-awareness-manager:
    container_name: context-awareness-manager
    image: "${REGISTRY_NAME}/context-awareness-manager:${TAG}"
    restart: always
    ports:
      - 8080:8080
    environment:
      DOCKER_SERVER: "localhost:5000"
      AGENT_ID: ${AGENT_ID}
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zenoh-router:
    container_name: zenoh-router
    image: eclipse/zenoh:1.0.1
    restart: unless-stopped
    ports:
      - 7447:7447
      - 8000:8000
    environment:
      RUST_LOG: "debug"
    volumes:
      - ./zenoh-router/zenoh_config.json5:/zenoh_config.json5:ro
    command: -c /zenoh_config.json5

  sla-manager:
    container_name: sla-manager
    image: "${REGISTRY_NAME}/sla-manager:${TAG}"
    restart: always
    ports:
      - 8081:8080
      - 8099:8099
    environment:
      PROMETHEUS_ADDRESS: "http://prometheus:9090"
      MONITORING_ADAPTER: "prometheus"
      GRPC_PORT: "8099"
    depends_on:
      - prometheus

  metrics-etl:
    container_name: metrics-etl
    image: "${REGISTRY_NAME}/metrics-etl:${TAG}"
    restart: always
    ports:
      - 8999:8999
    environment:
      AGENT_ID: ${AGENT_ID}
      VERSION: ${TAG}
    volumes:
      - ./zenoh-client:/app/zenoh-client
    depends_on:
      - prometheus
      - zenoh-router

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: always
    ports:
      - 9100:9100

volumes:
  prometheus-data:
