services:
  backend:
    container_name: controlpanel-backend
    image: "${REGISTRY_NAME}/controlpanel-backend:${TAG}"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./services:/app/uploads
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mydb
    depends_on:
      - db

  frontend:
    container_name: controlpanel-frontend
    image: "${REGISTRY_NAME}/controlpanel-frontend:${TAG}"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
