services:
  deployment-tool:
    image: "${REGISTRY_NAME}/deployment-tool:${TAG}"
    container_name: deployment-tool
    restart: always
    ports:
      - 8765:8000
    volumes:
      - ./services:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker:/root/.docker
    environment:
      - ZENOH_CONFIG_FILE=config/zenoh_config.json5