services:
  deployment-tool:
    image: "${REGISTRY_NAME}/deployment-tool:${TAG}"
    container_name: deployment-tool
    restart: always
    ports:
      - 8765:8000
    environment:
      DOCKER_SERVER: "localhost:5000"
    # Opciones de seguridad para permitir a Buildah construir imágenes
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./services:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - registry

  # Local Docker registry (acting as DockerHub for storing images)
  registry:
    image: registry:2
    container_name: local-registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry # Store the registry data in a local directory

# Volumes can be used for persisting registry data (optional)
volumes:
  registry-data:
    driver: local
