services:
  containerengine:
    container_name: containerengine
    image: jrubioc0/containerengine
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  context-awareness:
    container_name: context-awareness
    image: jrubioc0/context-awareness
    restart: always
    ports:
      - 8080:8080
    environment:
      DOCKERENGINE_URL: "http://containerengine:9000/deploy"
    depends_on:
      - containerengine

  sla-manager:
    container_name: sla-manager
    image: sla-manager:latest
    restart: always
    ports:
      - 8081:8080
      - 8099:8099
    environment:
      PROMETHEUS_ADDRESS: "http://prometheus:9090"
      MONITORING_ADAPTER: "prometheus"
      GRPC_PORT: "8099"
    depends_on:
      - prometheus

  colmena-role:
    container_name: colmena-role
    image: prhcatbsc/test_contextpublisher
