services:
  containerengine:
    container_name: containerengine
    image: jrubioc0/containerengine
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  zenoh:
    container_name: zenoh
    image: eclipse/zenoh:0.11.0
    restart: unless-stopped
    ports:
      - 7447:7447
      - 8000:8000
    environment:
      RUST_LOG: "debug"
    volumes:
      - ../../tools/zenoh_config.json5:/zenoh_config.json5:ro
    command: -c /zenoh_config.json5

  context-awareness:
    container_name: context-awareness
    image: jrubioc0/context-awareness-manager
    restart: always
    ports:
      - 8080:8080
    environment:
      DOCKERENGINE_URL: "http://containerengine:9000/deploy"
    depends_on:
      - containerengine

  colmena-role:
    container_name: colmena-role
    image: prhcatbsc/test_contextpublisher
