name: Build and Push COLMENA Context Awareness Manager Module

# CICD only is activated when:
# - there is a push to a PR from any branch to any branch
# - the protected branches are updated
on:
  push:
    branches:
      - main
      - develop
    tags:
      - "*"
    paths:
      - "components/context-awareness-manager/**"
      - ".github/workflows/context-awareness-manager.yaml"
  pull_request:
    paths:
      - "components/context-awareness-manager/**"
      - ".github/workflows/context-awareness-manager.yaml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "context-awareness-manager"
      TAG: "1.0.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }} .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }}