name: Build and Push COLMENA SLA Manager Module

# CICD only is activated when:
# - there is a push to a PR from any branch to any branch
# - the protected branches are updated
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "components/sla-manager-svc/**"
      - ".github/workflows/sla-manager.yaml"
    tags:
      - '*'
  pull_request:
    paths:
      - "components/sla-manager-svc/**"
      - ".github/workflows/sla-manager.yaml"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "sla-manager"
      TAG: "1.0.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }} .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }}